<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>RSS Monki</title>
        <meta name="description" content="The HTML5 Herald">
        <meta name="author" content="SitePoint">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="public/css/bootstrap-responsive.min.css">
        <link rel="stylesheet" href="public/css/bootstrap.min.css">
        <link rel="stylesheet" href="public/css/styles.css?v=1.0">
        <script type="text/javascript" src="public/js/jquery-1.9.1.min.js"></script>
        <script type="text/javascript" src="public/js/bootstrap.min.js"></script>
        <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <style>
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
        </style>
        <script type="text/javascript">
            var aRssUrls = <?php echo json_encode($aRssUrls);?>;
        </script>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="brand" href="">RSS Monki</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="#">Home</a></li>
                            <li><a href="#about">About</a></li>
                            <li><a href="#contact">Contact</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                    <div class="span3">
                        <ul class="nav nav-pills nav-stacked">
                            <li class="active"><a id="subscibe-rss" href="#">Subscribe</a></li>
                        </ul>
                        <br/>
                            <div id="rss-sidebar"></div>
                        </ul>
                    </div>
                    <div class="span9">